-- YÜKSEK ŞUURA - MANUEL AİDAT ÜYELERİ V3
-- Aidat üyeliğini site/Auth üyeliğinden ayırır.

create table if not exists public.aidat_uyeleri (
  id bigint generated by default as identity primary key,
  ad_soyad text not null,
  notlar text,
  aktif boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

alter table public.aidat_uyeleri enable row level security;

drop policy if exists "public read aidat members" on public.aidat_uyeleri;
create policy "public read aidat members" on public.aidat_uyeleri
for select to anon, authenticated using (true);

drop policy if exists "admin manage aidat members" on public.aidat_uyeleri;
create policy "admin manage aidat members" on public.aidat_uyeleri
for all to authenticated using (public.is_suura_admin()) with check (public.is_suura_admin());

-- Mevcut site üyelerini bir kere başlangıç listesine aktarır; sonrasında manuel yönetilir.
insert into public.aidat_uyeleri(ad_soyad,created_by)
select p.full_name, p.id from public.profiles p
where p.is_active=true and coalesce(trim(p.full_name),'')<>''
and not exists(select 1 from public.aidat_uyeleri a where lower(a.ad_soyad)=lower(p.full_name));

alter table public.aidat_odemeleri add column if not exists aidat_uye_id bigint references public.aidat_uyeleri(id) on delete cascade;

-- Eski user_id kayıtları varsa ad üzerinden yeni manuel üyeye bağla.
update public.aidat_odemeleri o set aidat_uye_id=a.id
from public.profiles p, public.aidat_uyeleri a
where o.aidat_uye_id is null and o.user_id=p.id and lower(a.ad_soyad)=lower(p.full_name);

-- Yeni manuel sistem için unique anahtar.
create unique index if not exists aidat_odemeleri_donem_uye_unique
on public.aidat_odemeleri(donem_id,aidat_uye_id) where aidat_uye_id is not null;

-- user_id artık zorunlu değildir.
alter table public.aidat_odemeleri alter column user_id drop not null;

-- Public aidat verisini manuel üyelerden üret.
create or replace function public.get_public_aidat_data()
returns jsonb language sql security definer set search_path=public
as $$
select jsonb_build_object(
 'donemler',coalesce((select jsonb_agg(to_jsonb(d) order by d.yil desc,d.ay desc) from public.aidat_donemleri d),'[]'::jsonb),
 'odemeler',coalesce((select jsonb_agg(jsonb_build_object('donem_id',o.donem_id,'aidat_uye_id',o.aidat_uye_id,'durum',o.durum,'odenen_tutar',o.odenen_tutar,'odeme_tarihi',o.odeme_tarihi)) from public.aidat_odemeleri o where o.aidat_uye_id is not null),'[]'::jsonb),
 'uyeler',coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'full_name',a.ad_soyad,'username',null,'avatar_url',null) order by a.ad_soyad) from public.aidat_uyeleri a where a.aktif=true),'[]'::jsonb),
 'giderler',coalesce((select jsonb_agg(jsonb_build_object('id',g.id,'baslik',g.baslik,'aciklama',g.aciklama,'tutar',g.tutar,'gider_tarihi',g.gider_tarihi,'pdf_path',g.pdf_path) order by g.gider_tarihi desc) from public.aidat_giderleri g),'[]'::jsonb),
 'ozet',jsonb_build_object(
  'toplam_tahsilat',coalesce((select sum(o.odenen_tutar) from public.aidat_odemeleri o where o.durum='odendi'),0),
  'toplam_gider',coalesce((select sum(g.tutar) from public.aidat_giderleri g),0),
  'kasa_bakiyesi',coalesce((select sum(o.odenen_tutar) from public.aidat_odemeleri o where o.durum='odendi'),0)-coalesce((select sum(g.tutar) from public.aidat_giderleri g),0)
 )
);
$$;
revoke all on function public.get_public_aidat_data() from public;
grant execute on function public.get_public_aidat_data() to anon,authenticated;