-- Dijital Şûra V1: Supabase SQL Editor'de bir kez çalıştır
create table if not exists public.chat_channels (id bigint generated by default as identity primary key,name text unique not null,description text,sort_order int not null default 0,created_at timestamptz not null default now());
create table if not exists public.chat_messages (id bigint generated by default as identity primary key,channel_id bigint not null references public.chat_channels(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,display_name text not null,content text not null check(char_length(content) between 1 and 2000),created_at timestamptz not null default now());
insert into public.chat_channels(name,description,sort_order) values ('genel','Şûra genel sohbeti',1),('etkinlik','Etkinlik planları',2),('halısaha','Maç ve kadro planları',3),('oyun','Oyun geceleri',4),('anılar','Şûra anıları',5),('öneri','Öneri ve fikirler',6),('random','Serbest sohbet',7) on conflict(name) do nothing;
alter table public.chat_channels enable row level security; alter table public.chat_messages enable row level security;
create policy "auth read channels" on public.chat_channels for select to authenticated using(true);
create policy "auth read messages" on public.chat_messages for select to authenticated using(true);
create policy "auth insert own messages" on public.chat_messages for insert to authenticated with check(auth.uid()=user_id);
create policy "delete own messages" on public.chat_messages for delete to authenticated using(auth.uid()=user_id);
alter publication supabase_realtime add table public.chat_messages;