-- Yüksek Şuura • kanal mesajı tepkileri ve cevaplar
alter table public.chat_messages
  add column if not exists reply_to uuid references public.chat_messages(id) on delete set null;

create table if not exists public.chat_reactions (
  id bigint generated by default as identity primary key,
  message_id uuid not null references public.chat_messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null check (emoji in ('👍','❤️','😂','🐺')),
  created_at timestamptz not null default now(),
  unique(message_id,user_id,emoji)
);

alter table public.chat_reactions enable row level security;

drop policy if exists "members read reactions" on public.chat_reactions;
create policy "members read reactions" on public.chat_reactions
for select to authenticated using (true);

drop policy if exists "members add own reactions" on public.chat_reactions;
create policy "members add own reactions" on public.chat_reactions
for insert to authenticated with check (user_id=auth.uid());

drop policy if exists "members delete own reactions" on public.chat_reactions;
create policy "members delete own reactions" on public.chat_reactions
for delete to authenticated using (user_id=auth.uid());

do $$ begin
  alter publication supabase_realtime add table public.chat_reactions;
exception when duplicate_object then null;
end $$;
