-- Yüksek Şuura / Dijital Şuura Komut Motoru v1
create table if not exists public.system_commands (
 id bigint generated by default as identity primary key,
 command text not null unique,
 title text not null,
 response_template text not null,
 response_mode text not null default 'private' check (response_mode in ('private','channel')),
 is_active boolean not null default true,
 created_by uuid references auth.users(id) on delete set null,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 constraint system_commands_format check (command ~ '^[a-z0-9_]+$')
);
alter table public.system_commands enable row level security;
drop policy if exists "authenticated read active commands" on public.system_commands;
create policy "authenticated read active commands" on public.system_commands for select to authenticated using (is_active or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "admin manage commands" on public.system_commands;
create policy "admin manage commands" on public.system_commands for all to authenticated using (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check (exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
insert into public.system_commands(command,title,response_template,response_mode,is_active)
values
('yardim','Komut Yardımı','Kullanabileceğin komutlar yönetim tarafından belirlenir. Komutları / işareti ile başlatabilirsin.','private',true),
('aidat','Aidat Bilgisi','{{full_name}}, kişisel aidat bilgilerin burada görüntülenecek. Aidat entegrasyonu henüz aktif değil.','private',true)
on conflict(command) do nothing;

create or replace function public.run_system_command(p_command text,p_channel_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare c public.system_commands; p public.profiles; body text; msg public.chat_messages;
begin
 select * into p from public.profiles where id=auth.uid() and is_active=true;
 if p.id is null then raise exception 'Aktif üyelik gerekli.'; end if;
 select * into c from public.system_commands where command=lower(trim(leading '/' from p_command)) and is_active=true;
 if c.id is null then return jsonb_build_object('ok',false,'error','Komut bulunamadı. /yardim yazabilirsin.'); end if;
 body:=replace(replace(replace(c.response_template,'{{full_name}}',coalesce(p.full_name,'Üye')),'{{username}}',coalesce(p.username,'uye')),'{{command}}','/'||c.command);
 if c.command='yardim' then
   select 'Kullanılabilir komutlar: '||string_agg('/'||command,', ' order by command) into body from public.system_commands where is_active=true;
 end if;
 if c.response_mode='channel' then
   insert into public.chat_messages(channel_id,user_id,display_name,content,sender_type,system_name,announcement_type)
   values(p_channel_id,auth.uid(),'Dijital Şuura',body,'system','Dijital Şuura','bilgi') returning * into msg;
   return jsonb_build_object('ok',true,'mode','channel','message',to_jsonb(msg));
 end if;
 return jsonb_build_object('ok',true,'mode','private','content',body,'title',c.title);
end $$;
revoke all on function public.run_system_command(text,bigint) from public;
grant execute on function public.run_system_command(text,bigint) to authenticated;
