-- Dijital Şûra V1 / Etkinlik + Duyuru
create table if not exists public.events(
 id bigint generated by default as identity primary key,
 title text not null check(char_length(title) between 2 and 100),
 description text,
 category text not null default 'genel',
 location text,
 event_at timestamptz not null,
 created_by uuid not null references public.profiles(id),
 created_at timestamptz not null default now()
);
create table if not exists public.event_participants(
 event_id bigint references public.events(id) on delete cascade,
 user_id uuid references public.profiles(id) on delete cascade,
 status text not null default 'going' check(status in('going','maybe')),
 created_at timestamptz not null default now(),
 primary key(event_id,user_id)
);
create table if not exists public.announcements(
 id bigint generated by default as identity primary key,
 title text not null check(char_length(title) between 2 and 120),
 content text not null check(char_length(content) between 2 and 3000),
 pinned boolean not null default false,
 created_by uuid not null references public.profiles(id),
 created_at timestamptz not null default now()
);
alter table public.events enable row level security;
alter table public.event_participants enable row level security;
alter table public.announcements enable row level security;
drop policy if exists "members read events" on public.events;
drop policy if exists "admins manage events" on public.events;
drop policy if exists "members read participants" on public.event_participants;
drop policy if exists "members manage own participation" on public.event_participants;
drop policy if exists "members delete own participation" on public.event_participants;
drop policy if exists "members read announcements" on public.announcements;
drop policy if exists "admins manage announcements" on public.announcements;
create policy "members read events" on public.events for select to authenticated using(true);
create policy "admins manage events" on public.events for all to authenticated using(public.is_suura_admin()) with check(public.is_suura_admin());
create policy "members read participants" on public.event_participants for select to authenticated using(true);
create policy "members manage own participation" on public.event_participants for insert to authenticated with check(auth.uid()=user_id);
create policy "members delete own participation" on public.event_participants for delete to authenticated using(auth.uid()=user_id);
create policy "members read announcements" on public.announcements for select to authenticated using(true);
create policy "admins manage announcements" on public.announcements for all to authenticated using(public.is_suura_admin()) with check(public.is_suura_admin());