-- Dijital Şûra V1 / Galeri
create table if not exists public.gallery_items(
 id bigint generated by default as identity primary key,
 user_id uuid not null references public.profiles(id) on delete cascade,
 image_url text not null,
 storage_path text not null,
 caption text,
 created_at timestamptz not null default now()
);
alter table public.gallery_items enable row level security;
drop policy if exists "members read gallery" on public.gallery_items;
drop policy if exists "members add gallery" on public.gallery_items;
drop policy if exists "owners delete gallery" on public.gallery_items;
drop policy if exists "admins delete gallery" on public.gallery_items;
create policy "members read gallery" on public.gallery_items for select to authenticated using(true);
create policy "members add gallery" on public.gallery_items for insert to authenticated with check(auth.uid()=user_id);
create policy "owners delete gallery" on public.gallery_items for delete to authenticated using(auth.uid()=user_id);
create policy "admins delete gallery" on public.gallery_items for delete to authenticated using(public.is_suura_admin());
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('gallery','gallery',true,10485760,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict(id) do update set public=true,file_size_limit=10485760,allowed_mime_types=array['image/jpeg','image/png','image/webp','image/gif'];
drop policy if exists "public read gallery media" on storage.objects;
drop policy if exists "members upload gallery media" on storage.objects;
drop policy if exists "owners delete gallery media" on storage.objects;
create policy "public read gallery media" on storage.objects for select using(bucket_id='gallery');
create policy "members upload gallery media" on storage.objects for insert to authenticated with check(bucket_id='gallery' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "owners delete gallery media" on storage.objects for delete to authenticated using(bucket_id='gallery' and (storage.foldername(name))[1]=auth.uid()::text);