"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,Camera,ImagePlus,Trash2,X} from "lucide-react";
import "./gallery.css";
const db=createClient("https://kzhklbtdyzinfacaotuh.supabase.co","sb_publishable__FvHp-RV7UHiWF0H9Y5Tug_yfMGyTX9");
export default function Galeri(){
 const [session,setSession]=useState(null),[me,setMe]=useState(null),[items,setItems]=useState([]),[profiles,setProfiles]=useState({}),[caption,setCaption]=useState(""),[uploading,setUploading]=useState(false),[view,setView]=useState(null),[msg,setMsg]=useState("");
 async function load(){const {data:{session:s}}=await db.auth.getSession();setSession(s);if(!s)return;const [{data:p},{data:g},{data:ps}]=await Promise.all([db.from("profiles").select("*").eq("id",s.user.id).single(),db.from("gallery_items").select("*").order("created_at",{ascending:false}),db.from("profiles").select("id,full_name,username,avatar_url")]);setMe(p);setItems(g||[]);setProfiles(Object.fromEntries((ps||[]).map(x=>[x.id,x])))}
 useEffect(()=>{load()},[]);
 async function upload(e){const file=e.target.files?.[0];if(!file||!session)return;if(file.size>10485760){setMsg("Fotoğraf en fazla 10 MB olabilir.");return}if(!["image/jpeg","image/png","image/webp","image/gif"].includes(file.type)){setMsg("JPG, PNG, WebP veya GIF yükleyebilirsin.");return}setUploading(true);const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=session.user.id+"/"+Date.now()+"."+ext;const {error:ue}=await db.storage.from("gallery").upload(path,file,{contentType:file.type});if(ue){setMsg(ue.message);setUploading(false);return}const {data}=db.storage.from("gallery").getPublicUrl(path);const {error}=await db.from("gallery_items").insert({user_id:session.user.id,image_url:data.publicUrl,storage_path:path,caption:caption.trim()||null});setUploading(false);if(error)setMsg(error.message);else{setCaption("");setMsg("Fotoğraf galeriye eklendi ✓");load()}e.target.value=""}
 async function remove(x){if(!confirm("Bu fotoğraf galeriden silinsin mi?"))return;const {error}=await db.from("gallery_items").delete().eq("id",x.id);if(error){setMsg(error.message);return}if(x.user_id===session.user.id)await db.storage.from("gallery").remove([x.storage_path]);setView(null);load()}
 if(!session)return <main className="galleryGate"><Camera/><h1>Şûra galerisi üyelere özel</h1><a href="/">Giriş sayfasına dön</a></main>;
 return <main className="galleryPage"><header><a href="/"><ArrowLeft size={18}/> Dijital Şûra</a><b>ŞÛRA GALERİSİ</b></header><section className="galleryHero"><p>YÜKSEK ŞÛRA • ANILAR</p><h1>Bizden kalan kareler.</h1><span>Etkinliklerden, buluşmalardan ve yıllardır biriken Şûra anılarından.</span></section><section className="uploadBox"><div><ImagePlus/><span><b>Galeriye fotoğraf ekle</b><small>JPG, PNG, WebP veya GIF • Maks. 10 MB</small></span></div><input placeholder="Kısa bir açıklama (isteğe bağlı)" maxLength={180} value={caption} onChange={e=>setCaption(e.target.value)}/><label className={uploading?"disabled":""}>{uploading?"Yükleniyor…":"Fotoğraf Seç"}<input disabled={uploading} type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload}/></label></section>{msg&&<div className="galleryNotice">{msg}</div>}<section className="grid">{items.map(x=>{const p=profiles[x.user_id];return <article key={x.id} onClick={()=>setView(x)}><img src={x.image_url} alt={x.caption||"Şûra galerisi"}/><div className="shade"><b>{x.caption||"Şûra Anısı"}</b><span>{p?.full_name||"Şûra Üyesi"} • {new Date(x.created_at).toLocaleDateString("tr-TR")}</span></div></article>})}{items.length===0&&<div className="empty">İlk Şûra karesini sen ekle 📸</div>}</section>{view&&<div className="lightbox" onClick={()=>setView(null)}><button className="close"><X/></button><div className="lightContent" onClick={e=>e.stopPropagation()}><img src={view.image_url} alt=""/><div><b>{view.caption||"Şûra Anısı"}</b><span>{profiles[view.user_id]?.full_name||"Şûra Üyesi"}</span>{(view.user_id===session.user.id||me?.role==="admin")&&<button className="remove" onClick={()=>remove(view)}><Trash2 size={14}/> Fotoğrafı Sil</button>}</div></div></div>}</main>}