"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CalendarDays,MapPin,Pin,Users,MessageCircle,ThumbsUp,ThumbsDown} from "lucide-react";
import "./events.css";
const db=createClient("https://kzhklbtdyzinfacaotuh.supabase.co","sb_publishable__FvHp-RV7UHiWF0H9Y5Tug_yfMGyTX9");
export default function Etkinlikler(){
 const [session,setSession]=useState(null),[events,setEvents]=useState([]),[parts,setParts]=useState([]),[notes,setNotes]=useState([]),[comments,setComments]=useState([]),[texts,setTexts]=useState({}),[loading,setLoading]=useState(true);
 async function load(){const {data:{session:s}}=await db.auth.getSession();setSession(s);if(!s){setLoading(false);return}const [{data:e},{data:p},{data:n},{data:c}]=await Promise.all([db.from("events").select("*").order("event_at"),db.from("event_participants").select("*"),db.from("announcements").select("*").order("pinned",{ascending:false}).order("created_at",{ascending:false}),db.from("event_comments").select("*,profiles(full_name,username,avatar_url)").order("created_at")]);setEvents(e||[]);setParts(p||[]);setNotes(n||[]);setComments(c||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function rsvp(id,status){await db.from("event_participants").upsert({event_id:id,user_id:session.user.id,status},{onConflict:"event_id,user_id"});load()}
 async function comment(id){const content=(texts[id]||"").trim();if(!content)return;const {error}=await db.from("event_comments").insert({event_id:id,user_id:session.user.id,content});if(!error){setTexts(v=>({...v,[id]:""}));load()}}
 if(loading)return <main className="eventGate">Etkinlikler yükleniyor…</main>;
 if(!session)return <main className="eventGate"><CalendarDays/><h1>Şûra üyelerine özel</h1><a href="/">Giriş sayfasına dön</a></main>;
 return <main className="eventsPage"><header><a href="/"><ArrowLeft size={18}/> Dijital Şuura</a><div className="eventNav"><a href="/secim">Seçim Merkezi</a><b>ETKİNLİKLER</b></div></header><section className="hero"><p>YÜKSEK ŞÛRA • TAKVİM</p><h1>Birlikte olduğumuz anlar.</h1><span>Planlanan buluşmalar, katılım durumları ve üye yorumları.</span></section>{notes.length>0&&<section className="announcements"><h2>Duyurular</h2>{notes.map(n=><article key={n.id}>{n.pinned&&<Pin size={13}/>}<div><b>{n.title}</b><p>{n.content}</p></div></article>)}</section>}<section className="eventSection"><div className="sectionTitle"><h2>Yaklaşan Etkinlikler</h2><span>{events.length} etkinlik</span></div><div className="eventGrid">{events.map(e=>{const going=parts.filter(p=>p.event_id===e.id&&p.status==="going").length,no=parts.filter(p=>p.event_id===e.id&&p.status==="not_going").length,mine=parts.find(p=>p.event_id===e.id&&p.user_id===session.user.id),d=new Date(e.event_at),cs=comments.filter(x=>x.event_id===e.id);return <article className="eventCard eventCardV7" key={e.id}>{e.image_url&&<img className="eventCover" src={e.image_url} alt={e.title}/>}<div className="eventBody"><div className="date"><b>{d.toLocaleDateString("tr-TR",{day:"2-digit"})}</b><span>{d.toLocaleDateString("tr-TR",{month:"short"}).toUpperCase()}</span></div><div className="eventInfo"><i>{e.category}</i><h3>{e.title}</h3>{e.description&&<p>{e.description}</p>}<div className="meta"><span><CalendarDays size={13}/>{d.toLocaleString("tr-TR",{hour:"2-digit",minute:"2-digit"})}</span>{e.location&&<span><MapPin size={13}/>{e.location}</span>}<span><Users size={13}/>{going} katılıyor · {no} katılmıyor</span></div><div className="rsvp"><button className={mine?.status==="going"?"joined":""} onClick={()=>rsvp(e.id,"going")}><ThumbsUp size={14}/> Katılıyorum</button><button className={mine?.status==="not_going"?"notGoing":""} onClick={()=>rsvp(e.id,"not_going")}><ThumbsDown size={14}/> Katılmıyorum</button></div></div></div><div className="eventComments"><h4><MessageCircle size={15}/> Yorumlar <span>{cs.length}</span></h4>{cs.map(x=><div className="eventComment" key={x.id}><b>{x.profiles?.full_name||"Üye"}</b><p>{x.content}</p></div>)}<div className="commentForm"><input maxLength={1000} placeholder="Etkinlik hakkında yorum yaz…" value={texts[e.id]||""} onChange={x=>setTexts(v=>({...v,[e.id]:x.target.value}))}/><button onClick={()=>comment(e.id)}>Gönder</button></div></div></article>})}{events.length===0&&<div className="empty">Henüz planlanmış etkinlik yok.</div>}</div></section></main>
}