"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CalendarDays,MapPin,Pin,Users} from "lucide-react";
import "./events.css";
const db=createClient("https://kzhklbtdyzinfacaotuh.supabase.co","sb_publishable__FvHp-RV7UHiWF0H9Y5Tug_yfMGyTX9");
export default function Etkinlikler(){
 const [session,setSession]=useState(null),[events,setEvents]=useState([]),[parts,setParts]=useState([]),[notes,setNotes]=useState([]),[loading,setLoading]=useState(true);
 async function load(){const {data:{session:s}}=await db.auth.getSession();setSession(s);if(!s){setLoading(false);return}const [{data:e},{data:p},{data:n}]=await Promise.all([db.from("events").select("*").order("event_at"),db.from("event_participants").select("*"),db.from("announcements").select("*").order("pinned",{ascending:false}).order("created_at",{ascending:false})]);setEvents(e||[]);setParts(p||[]);setNotes(n||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function join(id){const mine=parts.find(p=>p.event_id===id&&p.user_id===session.user.id);if(mine){await db.from("event_participants").delete().eq("event_id",id).eq("user_id",session.user.id)}else{await db.from("event_participants").insert({event_id:id,user_id:session.user.id,status:"going"})}load()}
 if(loading)return <main className="eventGate">Etkinlikler yükleniyor…</main>;
 if(!session)return <main className="eventGate"><CalendarDays/><h1>Şûra üyelerine özel</h1><a href="/">Giriş sayfasına dön</a></main>;
 return <main className="eventsPage"><header><a href="/"><ArrowLeft size={18}/> Dijital Şûra</a><b>ETKİNLİKLER</b></header><section className="hero"><p>YÜKSEK ŞÛRA • TAKVİM</p><h1>Birlikte olduğumuz anlar.</h1><span>Planlanan buluşmalar, organizasyonlar ve Şûra duyuruları.</span></section>{notes.length>0&&<section className="announcements"><h2>Duyurular</h2>{notes.map(n=><article key={n.id}>{n.pinned&&<Pin size={13}/>}<div><b>{n.title}</b><p>{n.content}</p></div></article>)}</section>}<section className="eventSection"><div className="sectionTitle"><h2>Yaklaşan Etkinlikler</h2><span>{events.length} etkinlik</span></div><div className="eventGrid">{events.map(e=>{const count=parts.filter(p=>p.event_id===e.id&&p.status==="going").length;const joined=parts.some(p=>p.event_id===e.id&&p.user_id===session.user.id);const d=new Date(e.event_at);return <article className="eventCard" key={e.id}><div className="date"><b>{d.toLocaleDateString("tr-TR",{day:"2-digit"})}</b><span>{d.toLocaleDateString("tr-TR",{month:"short"}).toUpperCase()}</span></div><div className="eventInfo"><i>{e.category}</i><h3>{e.title}</h3>{e.description&&<p>{e.description}</p>}<div className="meta"><span><CalendarDays size={13}/>{d.toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"})}</span>{e.location&&<span><MapPin size={13}/>{e.location}</span>}<span><Users size={13}/>{count} katılıyor</span></div><button className={joined?"joined":""} onClick={()=>join(e.id)}>{joined?"✓ Katılıyorum":"Katılacağım"}</button></div></article>})}{events.length===0&&<div className="empty">Henüz planlanmış etkinlik yok.</div>}</div></section></main>}