"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,CalendarPlus,Megaphone,Pin,Trash2} from "lucide-react";
import "./content.css";
const db=createClient("https://kzhklbtdyzinfacaotuh.supabase.co","sb_publishable__FvHp-RV7UHiWF0H9Y5Tug_yfMGyTX9");
export default function Icerik(){
 const [me,setMe]=useState(null),[events,setEvents]=useState([]),[notes,setNotes]=useState([]),[msg,setMsg]=useState("");
 const [event,setEvent]=useState({title:"",description:"",category:"genel",location:"",event_at:""});
 const [note,setNote]=useState({title:"",content:"",pinned:false});
 async function load(){const {data:{session}}=await db.auth.getSession();if(!session)return;const {data:p}=await db.from("profiles").select("*").eq("id",session.user.id).single();setMe(p);if(p?.role!=="admin")return;const [{data:e},{data:n}]=await Promise.all([db.from("events").select("*").order("event_at"),db.from("announcements").select("*").order("created_at",{ascending:false})]);setEvents(e||[]);setNotes(n||[])}
 useEffect(()=>{load()},[]);
 async function addEvent(e){e.preventDefault();const {error}=await db.from("events").insert({...event,created_by:me.id,event_at:new Date(event.event_at).toISOString()});if(error)setMsg(error.message);else{setEvent({title:"",description:"",category:"genel",location:"",event_at:""});setMsg("Etkinlik yayınlandı ✓");load()}}
 async function addNote(e){e.preventDefault();const {error}=await db.from("announcements").insert({...note,created_by:me.id});if(error)setMsg(error.message);else{setNote({title:"",content:"",pinned:false});setMsg("Duyuru yayınlandı ✓");load()}}
 async function del(table,id){if(!confirm("Bu içerik silinsin mi?"))return;const {error}=await db.from(table).delete().eq("id",id);if(error)setMsg(error.message);else load()}
 if(!me)return <main className="contentGate">Yönetici oturumu bekleniyor…</main>;
 if(me.role!=="admin")return <main className="contentGate">Bu alan yöneticilere özel.</main>;
 return <main className="contentPage"><header><a href="/"><ArrowLeft size={17}/> Dijital Şûra</a><b>İÇERİK YÖNETİMİ</b></header><section className="intro"><p>YÜKSEK ŞÛRA • YAYIN MERKEZİ</p><h1>Etkinlik & Duyuru</h1><span>Ana yönetim panelinden bağımsız hızlı içerik ekranı.</span></section>{msg&&<div className="notice">{msg}</div>}<section className="forms"><form onSubmit={addEvent}><h2><CalendarPlus/> Yeni Etkinlik</h2><input required placeholder="Etkinlik adı" value={event.title} onChange={e=>setEvent({...event,title:e.target.value})}/><div className="row"><select value={event.category} onChange={e=>setEvent({...event,category:e.target.value})}><option value="genel">Genel</option><option value="halısaha">Halısaha</option><option value="okey">Okey / 101</option><option value="yüzme">Yüzme</option><option value="kafe">Kafe</option><option value="maç">Maç İzleme</option><option value="özel">Özel</option></select><input required type="datetime-local" value={event.event_at} onChange={e=>setEvent({...event,event_at:e.target.value})}/></div><input placeholder="Konum" value={event.location} onChange={e=>setEvent({...event,location:e.target.value})}/><textarea placeholder="Açıklama" value={event.description} onChange={e=>setEvent({...event,description:e.target.value})}/><button>Etkinliği Yayınla</button></form><form onSubmit={addNote}><h2><Megaphone/> Yeni Duyuru</h2><input required placeholder="Duyuru başlığı" value={note.title} onChange={e=>setNote({...note,title:e.target.value})}/><textarea required placeholder="Duyuru metni" value={note.content} onChange={e=>setNote({...note,content:e.target.value})}/><label className="check"><input type="checkbox" checked={note.pinned} onChange={e=>setNote({...note,pinned:e.target.checked})}/><Pin size={14}/> Üste sabitle</label><button>Duyuruyu Yayınla</button></form></section><section className="lists"><div><h3>Etkinlikler</h3>{events.map(x=><article key={x.id}><span><b>{x.title}</b><small>{new Date(x.event_at).toLocaleString("tr-TR")}</small></span><button onClick={()=>del("events",x.id)}><Trash2 size={14}/></button></article>)}</div><div><h3>Duyurular</h3>{notes.map(x=><article key={x.id}><span><b>{x.pinned&&"📌 "}{x.title}</b><small>{new Date(x.created_at).toLocaleString("tr-TR")}</small></span><button onClick={()=>del("announcements",x.id)}><Trash2 size={14}/></button></article>)}</div></section></main>;
}