"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {ArrowRight,ShieldCheck} from "lucide-react";
import "./onboarding.css";
const db=createClient("https://kzhklbtdyzinfacaotuh.supabase.co","sb_publishable__FvHp-RV7UHiWF0H9Y5Tug_yfMGyTX9");
export default function IlkGiris(){
 const [session,setSession]=useState(null),[name,setName]=useState(""),[username,setUsername]=useState(""),[password,setPassword]=useState(""),[password2,setPassword2]=useState(""),[msg,setMsg]=useState("Davet bağlantın doğrulanıyor…"),[busy,setBusy]=useState(false);
 useEffect(()=>{db.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session){const {data:p}=await db.from("profiles").select("full_name,username").eq("id",data.session.user.id).single();setName(p?.full_name||data.session.user.user_metadata?.full_name||"");setUsername(p?.username||"");setMsg("")}else setMsg("Davet bağlantısı geçersiz veya süresi dolmuş olabilir.")});const {data:s}=db.auth.onAuthStateChange(async(_e,v)=>{if(v){setSession(v);const {data:p}=await db.from("profiles").select("full_name,username").eq("id",v.user.id).single();setName(p?.full_name||v.user.user_metadata?.full_name||"");setUsername(p?.username||"");setMsg("")}});return()=>s.subscription.unsubscribe()},[]);
 async function finish(e){e.preventDefault();if(password.length<8){setMsg("Şifre en az 8 karakter olmalı.");return}if(password!==password2){setMsg("Şifreler eşleşmiyor.");return}if(!/^[a-z0-9._]{3,30}$/.test(username)){setMsg("Kullanıcı adı 3–30 karakter; küçük harf, rakam, nokta veya alt çizgi kullan.");return}setBusy(true);setMsg("");const {error:a}=await db.auth.updateUser({password,data:{...session.user.user_metadata,onboarding_required:false}});if(a){setBusy(false);setMsg(a.message);return}const {error:b}=await db.from("profiles").update({full_name:name.trim(),username}).eq("id",session.user.id);setBusy(false);if(b){setMsg(b.code==="23505"?"Bu kullanıcı adı kullanılıyor.":b.message);return}await db.auth.signOut();location.href="/?uye=hazir"}
 return <main className="onboard"><section><div className="seal"><ShieldCheck/></div><small>YÜKSEK ŞUURA • ÜYE DAVETİ</small><h1>Şuura hesabını tamamla.</h1><p>Davetin onaylandı. Kendi giriş bilgilerini belirledikten sonra Dijital Şuura'ya geçeceksin.</p>{session?<form onSubmit={finish}><label>Ad Soyad</label><input value={name} onChange={e=>setName(e.target.value)} required/><label>Kullanıcı Adı</label><input value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="ornek.uye" required/><label>E-posta</label><input type="email" value={session?.user?.email||""} disabled/><label>Yeni Şifre</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/><label>Yeni Şifre Tekrar</label><input type="password" value={password2} onChange={e=>setPassword2(e.target.value)} minLength={8} required/><button disabled={busy}>{busy?"Hesap hazırlanıyor…":"Hesabımı Tamamla"} <ArrowRight size={17}/></button></form>:<a href="/">Ana sayfaya dön</a>}{msg&&<div className="notice">{msg}</div>}</section></main>
}