"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,Camera,Check,KeyRound,ShieldCheck,User} from "lucide-react";
import "./profile.css";
const db=createClient("https://kzhklbtdyzinfacaotuh.supabase.co","sb_publishable__FvHp-RV7UHiWF0H9Y5Tug_yfMGyTX9");
export default function Profil(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[form,setForm]=useState({full_name:"",username:""}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[pass,setPass]=useState({current:"",next:"",again:""}),[passBusy,setPassBusy]=useState(false),[passMsg,setPassMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:{session:s}}=await db.auth.getSession();setSession(s);if(s){const {data}=await db.from("profiles").select("*").eq("id",s.user.id).single();setProfile(data);setForm({full_name:data?.full_name||"",username:data?.username||""})}setLoading(false)})()},[]);
 async function save(e){e.preventDefault();const username=form.username.trim().toLowerCase();if(username&&!/^[a-z0-9._]{3,30}$/.test(username)){setMsg("Kullanıcı adı 3–30 karakter; harf, rakam, nokta ve alt çizgi kullan.");return}setSaving(true);const {data,error}=await db.from("profiles").update({full_name:form.full_name.trim(),username:username||null}).eq("id",session.user.id).select().single();setSaving(false);if(error)setMsg(error.code==="23505"?"Bu kullanıcı adı başka bir üyede kullanılıyor.":error.message);else{setProfile(data);setMsg("Profil kaydedildi ✓")}}
 async function changePassword(e){e.preventDefault();setPassMsg("");if(pass.next.length<8)return setPassMsg("Yeni şifre en az 8 karakter olmalı.");if(pass.next!==pass.again)return setPassMsg("Yeni şifreler eşleşmiyor.");setPassBusy(true);const {error:reauth}=await db.auth.signInWithPassword({email:session.user.email,password:pass.current});if(reauth){setPassBusy(false);return setPassMsg("Mevcut şifren yanlış.");}const {error}=await db.auth.updateUser({password:pass.next});setPassBusy(false);if(error)return setPassMsg(error.message);setPass({current:"",next:"",again:""});setPassMsg("Şifren başarıyla değiştirildi ✓")}
 async function avatar(e){const file=e.target.files?.[0];if(!file)return;if(file.size>5242880){setMsg("Fotoğraf en fazla 5 MB olabilir.");return}const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=session.user.id+"/avatar."+ext;const {error}=await db.storage.from("avatars").upload(path,file,{upsert:true,contentType:file.type});if(error){setMsg(error.message);return}const {data}=db.storage.from("avatars").getPublicUrl(path);const url=data.publicUrl+"?v="+Date.now();const {error:pe}=await db.from("profiles").update({avatar_url:url}).eq("id",session.user.id);if(pe)setMsg(pe.message);else{setProfile(p=>({...p,avatar_url:url}));setMsg("Profil fotoğrafı güncellendi ✓")}}
 if(loading)return <main className="profileGate">Profil yükleniyor…</main>;
 if(!session)return <main className="profileGate"><User/><h1>Giriş yapman gerekiyor</h1><a href="/">Ana sayfaya dön</a></main>;
 return <main className="profilePage"><header><a href="/"><ArrowLeft size={18}/> Dijital Şuura</a><b>ÜYE PROFİLİ</b></header><section className="profileCard"><div className="cover"><span>YÜKSEK ŞUURA</span></div><div className="avatarWrap"><label>{profile?.avatar_url?<img src={profile.avatar_url} alt="Profil"/>:<User/>}<i><Camera size={15}/></i><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={avatar}/></label></div><div className="title"><h1>{profile?.full_name||"Şuura Üyesi"}</h1><p>@{profile?.username||"kullaniciadi"}</p><span className={profile?.role==="admin"?"adminBadge":profile?.role==="moderator"?"modBadge":"memberBadge"}>{profile?.role==="admin"?<><ShieldCheck size={12}/> YÖNETİCİ</>:profile?.role==="moderator"?"MODERATÖR":"ÜYE"}</span></div><form onSubmit={save}><label>AD SOYAD<input maxLength={60} required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>KULLANICI ADI<div className="username"><span>@</span><input maxLength={30} value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="kullaniciadi"/></div><small>3–30 karakter • a-z, 0-9, nokta ve alt çizgi</small></label>{msg&&<div className="notice">{msg}</div>}<button disabled={saving}><Check size={16}/>{saving?"Kaydediliyor…":"Değişiklikleri Kaydet"}</button></form><form className="passwordForm" onSubmit={changePassword}><div className="formTitle"><KeyRound size={17}/><div><b>Şifreyi Değiştir</b><span>Güvenliğin için önce mevcut şifreni doğrula.</span></div></div><label>MEVCUT ŞİFRE<input type="password" autoComplete="current-password" value={pass.current} onChange={e=>setPass({...pass,current:e.target.value})} required/></label><label>YENİ ŞİFRE<input type="password" autoComplete="new-password" minLength={8} value={pass.next} onChange={e=>setPass({...pass,next:e.target.value})} required/></label><label>YENİ ŞİFRE TEKRAR<input type="password" autoComplete="new-password" minLength={8} value={pass.again} onChange={e=>setPass({...pass,again:e.target.value})} required/></label>{passMsg&&<div className="notice">{passMsg}</div>}<button disabled={passBusy}><KeyRound size={16}/>{passBusy?"Değiştiriliyor…":"Şifreyi Değiştir"}</button></form><footer><span>Hesap e-postası</span><b>{session.user.email}</b></footer></section></main>;
}