"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
import {ArrowLeft,Camera,Check,ShieldCheck,User} from "lucide-react";
import "./profile.css";
const db=createClient("https://kzhklbtdyzinfacaotuh.supabase.co","sb_publishable__FvHp-RV7UHiWF0H9Y5Tug_yfMGyTX9");
export default function Profil(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[form,setForm]=useState({full_name:"",username:""}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{(async()=>{const {data:{session:s}}=await db.auth.getSession();setSession(s);if(s){const {data}=await db.from("profiles").select("*").eq("id",s.user.id).single();setProfile(data);setForm({full_name:data?.full_name||"",username:data?.username||""})}setLoading(false)})()},[]);
 async function save(e){e.preventDefault();const username=form.username.trim().toLowerCase();if(username&&!/^[a-z0-9._]{3,30}$/.test(username)){setMsg("Kullanıcı adı 3–30 karakter; harf, rakam, nokta ve alt çizgi kullan.");return}setSaving(true);const {data,error}=await db.from("profiles").update({full_name:form.full_name.trim(),username:username||null}).eq("id",session.user.id).select().single();setSaving(false);if(error)setMsg(error.code==="23505"?"Bu kullanıcı adı başka bir üyede kullanılıyor.":error.message);else{setProfile(data);setMsg("Profil kaydedildi ✓")}}
 async function avatar(e){const file=e.target.files?.[0];if(!file)return;if(file.size>5242880){setMsg("Fotoğraf en fazla 5 MB olabilir.");return}const ext=(file.name.split(".").pop()||"jpg").toLowerCase();const path=session.user.id+"/avatar."+ext;const {error}=await db.storage.from("avatars").upload(path,file,{upsert:true,contentType:file.type});if(error){setMsg(error.message);return}const {data}=db.storage.from("avatars").getPublicUrl(path);const url=data.publicUrl+"?v="+Date.now();const {error:pe}=await db.from("profiles").update({avatar_url:url}).eq("id",session.user.id);if(pe)setMsg(pe.message);else{setProfile(p=>({...p,avatar_url:url}));setMsg("Profil fotoğrafı güncellendi ✓")}}
 if(loading)return <main className="profileGate">Profil yükleniyor…</main>;
 if(!session)return <main className="profileGate"><User/><h1>Giriş yapman gerekiyor</h1><a href="/">Ana sayfaya dön</a></main>;
 return <main className="profilePage"><header><a href="/"><ArrowLeft size={18}/> Dijital Şûra</a><b>ÜYE PROFİLİ</b></header><section className="profileCard"><div className="cover"><span>YÜKSEK ŞÛRA</span></div><div className="avatarWrap"><label>{profile?.avatar_url?<img src={profile.avatar_url} alt="Profil"/>:<User/>}<i><Camera size={15}/></i><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={avatar}/></label></div><div className="title"><h1>{profile?.full_name||"Şûra Üyesi"}</h1><p>@{profile?.username||"kullaniciadi"}</p><span className={profile?.role==="admin"?"adminBadge":"memberBadge"}>{profile?.role==="admin"?<><ShieldCheck size={12}/> ADMIN</>:"ÜYE"}</span></div><form onSubmit={save}><label>AD SOYAD<input maxLength={60} required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>KULLANICI ADI<div className="username"><span>@</span><input maxLength={30} value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="kullaniciadi"/></div><small>3–30 karakter • a-z, 0-9, nokta ve alt çizgi</small></label>{msg&&<div className="notice">{msg}</div>}<button disabled={saving}><Check size={16}/>{saving?"Kaydediliyor…":"Değişiklikleri Kaydet"}</button></form><footer><span>Hesap e-postası</span><b>{session.user.email}</b></footer></section></main>